'use strict';
(() => {
  const state={map:null,canvas:null,ctx:null,enabled:true,storm:null,raf:0,dpr:1,last:0,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const rad=d=>d*Math.PI/180;
  function destination(p,bearing,km){const d=km/6371,t=rad(bearing),p1=rad(p.lat),l1=rad(p.lon);const p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(t));const l2=l1+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return {lat:p2*180/Math.PI,lon:((l2*180/Math.PI+540)%360)-180};}
  function resize(){if(!state.map||!state.canvas)return;const rect=state.map.getContainer().getBoundingClientRect();state.dpr=Math.min(2,devicePixelRatio||1);state.canvas.width=Math.max(1,Math.round(rect.width*state.dpr));state.canvas.height=Math.max(1,Math.round(rect.height*state.dpr));state.canvas.style.width=rect.width+'px';state.canvas.style.height=rect.height+'px';state.ctx.setTransform(state.dpr,0,0,state.dpr,0,0);}
  function project(p){const q=state.map.project([p.lon,p.lat]);return {x:q.x,y:q.y};}
  function radiusPx(center,km){const a=project(center),b=project(destination(center,90,km));return Math.max(5,Math.hypot(b.x-a.x,b.y-a.y));}
  function windColor(ms){if(ms>=51)return '#8b5cf6';if(ms>=42)return '#e84b5b';if(ms>=33)return '#f97316';if(ms>=25)return '#eab308';return '#1499bd';}
  function drawRing(ctx,c,r,color,label,dashed=false,alpha=.75){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=1.5;if(dashed)ctx.setLineDash([6,6]);ctx.beginPath();ctx.arc(c.x,c.y,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.font='600 11px system-ui';ctx.fillStyle=color;ctx.fillText(label,c.x+r+5,c.y-3);ctx.restore();}
  function drawArrows(ctx,c,r,rotation,color,count=12){ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.globalAlpha=.58;ctx.lineWidth=1.4;for(let i=0;i<count;i++){const a=rotation+i*Math.PI*2/count;const x=c.x+Math.cos(a)*r,y=c.y+Math.sin(a)*r;const tangent=a+(state.storm.lat>=0?-Math.PI/2:Math.PI/2);const len=clamp(r*.16,7,18);const x2=x+Math.cos(tangent)*len,y2=y+Math.sin(tangent)*len;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();const h=4;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(tangent-.55)*h,y2-Math.sin(tangent-.55)*h);ctx.lineTo(x2-Math.cos(tangent+.55)*h,y2-Math.sin(tangent+.55)*h);ctx.closePath();ctx.fill();}ctx.restore();}
  function drawTrackParticles(ctx,track,progress,t){if(!track||track.length<2)return;const pts=track.map(project);const n=Math.max(12,Math.min(42,track.length*5));ctx.save();for(let i=0;i<n;i++){const u=((i/n)+(t*.000035))%1;const maxSeg=Math.max(1,Math.min(track.length-1,Math.ceil(progress*(track.length-1))));const f=u*maxSeg,idx=Math.min(maxSeg-1,Math.floor(f)),a=pts[idx],b=pts[idx+1],q=f-idx;const x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q;ctx.globalAlpha=.16+.55*(i/n);ctx.fillStyle=track[idx+1]?.forecast?'#f97316':'#0799bc';ctx.beginPath();ctx.arc(x,y,2.2,0,Math.PI*2);ctx.fill();}ctx.restore();}
  function drawCore(ctx,c,storm){const wind=Number(storm.windMs)||25,pressure=Number(storm.pressureHpa)||990,color=windColor(wind);const core=clamp(10+(1010-pressure)*.22,11,26);ctx.save();const g=ctx.createRadialGradient(c.x,c.y,2,c.x,c.y,core*2.8);g.addColorStop(0,'rgba(255,255,255,.96)');g.addColorStop(.18,'rgba(255,255,255,.85)');g.addColorStop(.38,color+'cc');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(c.x,c.y,core*2.8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff';ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(c.x,c.y,core*.48,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(10,40,50,.92)';ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.fillText(Math.round(wind)+' m/s',c.x,c.y-core*3.1);ctx.font='600 11px system-ui';ctx.fillText(Math.round(pressure)+' hPa',c.x,c.y-core*3.1+15);ctx.restore();}
  function draw(timestamp){state.raf=requestAnimationFrame(draw);if(!state.enabled||!state.storm||!state.map||!state.ctx)return;if(!state.map.isStyleLoaded?.())return;const ctx=state.ctx,rect=state.map.getContainer().getBoundingClientRect();ctx.clearRect(0,0,rect.width,rect.height);const s=state.storm;if(!Number.isFinite(+s.lat)||!Number.isFinite(+s.lon))return;const c=project(s);if(c.x<-200||c.y<-200||c.x>rect.width+200||c.y>rect.height+200)return;const t=state.reduced?0:timestamp;const spin=(s.lat>=0?-1:1)*t*.00016;const wind=Number(s.windMs)||25;const base=Number(s.radius34)||clamp(140+wind*5.2,180,500);const r34=radiusPx(s,base),r50=radiusPx(s,Number(s.radius50)||base*.58),r64=radiusPx(s,Number(s.radius64)||base*.34);drawTrackParticles(ctx,s.track,s.progress??1,t);drawRing(ctx,c,r34,'#f3a23b','34 kt',!s.officialRadii,.62);if(wind>=25)drawRing(ctx,c,r50,'#ef7c2f','50 kt',!s.officialRadii,.66);if(wind>=33)drawRing(ctx,c,r64,'#e84b5b','64 kt',!s.officialRadii,.72);drawArrows(ctx,c,r34*.78,spin,windColor(wind),14);drawArrows(ctx,c,r50*.78,spin*.9+1.1,windColor(wind),10);drawCore(ctx,c,s);}
  function attach(map,canvas){state.map=map;state.canvas=canvas;state.ctx=canvas.getContext('2d');resize();map.on('resize',resize);map.on('move',()=>{});if(!state.raf)state.raf=requestAnimationFrame(draw);}
  function setStorm(storm){state.storm=storm;}
  function setEnabled(v){state.enabled=!!v;if(!v&&state.ctx&&state.canvas)state.ctx.clearRect(0,0,state.canvas.width,state.canvas.height);}
  window.CycloneViz={attach,setStorm,setEnabled,resize,isAvailable:()=>!!document.createElement('canvas').getContext};
})();
